# Generated by Django 3.2.11 on 2022-01-24 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('cost_limit', models.CharField(choices=[('ANY', 'Без ограничения стоимости'), ('FIRST_RANGE', 'до 500 рублей'), ('SECOND_RANGE', '500-1000 рублей'), ('THIRD_RANGE', '1000-2000 рублей')], default='ANY', max_length=30, verbose_name='Стоимость подарка')),
                ('registration_end', models.DateField(verbose_name='Дата закрытия регистрации')),
                ('dispatch_date', models.DateField(verbose_name='Период отправки подарка')),
                ('slug', models.SlugField(default=games.models.get_slug, unique=True, verbose_name='Идентификатор игры')),
                ('owner_joined', models.BooleanField(default=False, verbose_name='Владелец присоединился к игре')),
                ('draw_done', models.BooleanField(default=False, verbose_name='Жеребьевка проведена?')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'игра',
                'verbose_name_plural': 'игры',
            },
        ),
    ]
