# Generated by Django 3.2.10 on 2021-12-24 09:28

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='owner_joined',
            field=models.BooleanField(default=False, verbose_name='Владелец присоединился к игре'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(default=games.models.get_slug, unique=True, verbose_name='Идентификатор игры'),
        ),
    ]
