# Generated by Django 3.2.10 on 2021-12-25 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20211224_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='games.game', verbose_name='Игра'),
        ),
    ]
