# Generated by Django 3.2.10 on 2021-12-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_profile_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='not_preferences',
            field=models.TextField(blank=True, null=True, verbose_name='Не хотел бы получить'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.TextField(blank=True, null=True, verbose_name='Хотел бы получить'),
        ),
    ]
