# Generated by Django 3.2.10 on 2021-12-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20211225_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='draw_done',
            field=models.BooleanField(default=False, verbose_name='Жеребьевка проведена?'),
        ),
    ]
