# Generated by Django 3.2.10 on 2021-12-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_draw_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='game',
        ),
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='players', to='games.Game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='game',
            name='registration_end',
            field=models.DateField(verbose_name='Дата закрытия регистрации'),
        ),
    ]
